//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MYBUSINESS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SO()
        {
            this.SODs = new HashSet<SOD>();
            this.Payments = new HashSet<Payment>();
        }
    
        public string Id { get; set; }
        public Nullable<int> SOSerial { get; set; }
        public decimal BillAmount { get; set; }
        public decimal BillPaid { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> PrevBalance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> SaleReturn { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> SODId { get; set; }
        public Nullable<decimal> SaleOrderAmount { get; set; }
        public Nullable<decimal> SaleReturnAmount { get; set; }
        public Nullable<decimal> SaleOrderQty { get; set; }
        public Nullable<decimal> SaleReturnQty { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentDetail { get; set; }
        public string Remarks { get; set; }
        public string Remarks2 { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOD> SODs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
    }
}
